{-# LANGUAGE ScopedTypeVariables #-}
module SymHask.SimplificationSpec (tests) where

import           Test.Tasty
import           Test.Tasty.HUnit
import           Test.Tasty.QuickCheck
import           SymHask.Symbolic
import           SymHask.Symbolic.Simplification.AutomaticSimplification
import           TestUtils ()
import Data.List.NonEmpty ( NonEmpty((:|)) )

tests :: TestTree
tests = testGroup "Simplification"
  [ unitTests
  , integrationTests
  , propertyTests 
  ]

-- ============================================================================
-- 1. Unit Tests (Deterministic verification of specific rules)
-- ============================================================================
unitTests :: TestTree
unitTests = testGroup "Unit Tests"
  [ testCase "Addition Identity: x + 0 -> x" $ do
      let x :: UnsimplifiedExpr = mkSymbol "x"
          expr = x + 0
      automaticSimplify expr @?= Right x
  
  , testCase "Multiplication Identity: x * 1 -> x" $ do
      let x :: UnsimplifiedExpr = mkSymbol "x"
          expr = x * 1
      automaticSimplify expr @?= Right x

  , testCase "Constant Folding: 2 + 3 -> 5" $ do
      let expr :: UnsimplifiedExpr = 2 + 3
      automaticSimplify expr @?= Right 5
      
  , testCase "Zero Property: x * 0 -> 0" $ do
      let x :: UnsimplifiedExpr = mkSymbol "x"
          expr = x * 0
      automaticSimplify expr @?= Right 0
  ]

-- ============================================================================
-- 2. Property Tests (Randomized verification of algebraic laws)
-- ============================================================================
propertyTests :: TestTree
propertyTests = testGroup "Algebraic Properties"
  [ testProperty "Commutativity of Sum: a + b == b + a" $ 
      \(a :: UnsimplifiedExpr) (b :: UnsimplifiedExpr) ->
        -- let inputLog = "Testing Commutativity of Sum with a: "
        --         ++ T.unpack (toHaskell a)
        --         ++ " and b: " ++ T.unpack (toHaskell b) ++ "\n"
        --  in trace inputLog $

        let left  = automaticSimplify $ a + b
            right = automaticSimplify $ b + a
        in left == right

  , testProperty "Idempotence: simplify(x) == simplify(simplify(x))" $
      \(x :: UnsimplifiedExpr) ->
        -- let inputLog = "Testing Idempotence with x: "
        --         ++ T.unpack (toHaskell x) ++ "\n"
        --  in trace inputLog $

        let res1 = automaticSimplify x
        in case res1 of
            Right s -> automaticSimplify s == Right s
            Left _  -> True -- Discard errors generated by random inputs
  ]

-- ============================================================================
-- 3. Integration Tests & Known Limitations
--    These simulate "Real World" complex usage and identify gaps.
-- ============================================================================
integrationTests :: TestTree
integrationTests = testGroup "Integration & Limitations"
  [ testGroup "Preliminary Successes" 
    [ testCase "Polynomial Expansion and Collection: 4*(y + 1) - 6(y + 1) -> -2(1 + y)" $ do
        -- Input: 4(y+1) - 6(y+1)
        -- Expected: -2(1 + y)
        let y = mkSymbol "y"
            expr = (4 * (y + 1)) - (6 * (y + 1)) :: UnsimplifiedExpr
        automaticSimplify expr @?= Right (mkNumber (-2) * (1 + y))
    , testCase "Rational Arithmetic: 1/2 + 1/3 -> 5/6" $ do
        let expr = mkFraction 1 2 + mkFraction 1 3
        automaticSimplify expr @?= Right (mkFraction 5 6)
    ]

  , testGroup "Identified Limitations (Future Work)"
    [ testCase "Trigonometric Identity: sin^2(x) + cos^2(x) -> 1" $ do

        let x = mkSymbol "x"
            sinX = mkFunction "sin" (x :| [])
            cosX = mkFunction "cos" (x :| [])
            expr = (sinX ** 2) + (cosX ** 2) :: UnsimplifiedExpr

        case automaticSimplify expr of
             Right res -> res /= mkNumber 1 @?
              "System lacks Trig simplification"
             Left _    -> return ()
    ]
  ]